version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backend/reports:/app/reports
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - apk-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - apk-network

networks:
  apk-network:
    driver: bridge

volumes:
  apk-data:
  apk-uploads:
